<?php

/**
 * BaseBookitCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $BookitBooks
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getBookitBooks() Returns the current record's "BookitBooks" collection
 * @method BookitCategory      setName()        Sets the current record's "name" value
 * @method BookitCategory      setBookitBooks() Sets the current record's "BookitBooks" collection
 * 
 * @package    bookitfree
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBookitCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bookit_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BookitBook as BookitBooks', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}