<?php

/**
 * BookitCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bookitfree
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BookitCategory extends BaseBookitCategory
{

  public function getActiveBooks($max = 2)
  {
    $q = $this->getActiveBooksQuery()
            ->limit($max)
            ;

    return $q->execute();
  }

  public function countActiveBooks()
  {
    return $this->getActiveBooksQuery()->count();
  }

  public function getActiveBooksQuery()
  {
    $q = Doctrine_Query::create()
            ->from('BookitBook j')
            ->where('j.category_id = ?', $this->getId());

    return Doctrine_Core::getTable('BookitBook')->addActiveBooksQuery($q);
  }

  public function getSlug()
  {
    return Bookit::slugify($this->getName());
  }

}