<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/30 00:22:49

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bookitfree',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
