<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/07/29 22:40:50
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_books_on_homepage' => 8,
  'app_max_books_on_category' => 8,
));
