<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/07/29 22:40:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bookitfree',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
