BookitCategory:
  actAs: { Timestampable: ~ }
  columns:
    name: { type: string(255), notnull: true, unique: true }
 
BookitBook:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    title:         { type: string(255) }
    secondary_title:         { type: string(255) }
    author:      { type: string(255), notnull: true }
    short_description:  { type: string(4000), notnull: true }
    description:  { type: string(4000), notnull: true }
    logo:         { type: string(255) }
    isbn:         { type: string(255), notnull: true }
    url:          { type: string(255) }
    pages:          { type: string(255) }
    dimensions:          { type: string(255) }
    weight:          { type: string(255) }
    position:     { type: string(255), notnull: true }
    location:     { type: string(255), notnull: true }
    how_to_apply: { type: string(4000), notnull: true }
#    token:        { type: string(255), notnull: true, unique: true }
    is_public:    { type: boolean, notnull: true, default: 1 }
    is_activated: { type: boolean, notnull: true, default: 0 }
    email:        { type: string(255), notnull: true }
    expires_at:   { type: timestamp, notnull: true }
    token:        { type: string(255), notnull: true, unique: true }
  relations:
    BookitCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: BookitBooks } 